// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.sky9th.game.chat.protos;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string networkID = 1;</code>
   * @return The networkID.
   */
  java.lang.String getNetworkID();
  /**
   * <code>string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  com.google.protobuf.ByteString
      getNetworkIDBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
