// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerList.proto

package com.sky9th.game.chat.protos;

public interface PlayerListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.PlayerList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  java.util.List<com.sky9th.game.chat.protos.PlayerInfo> 
      getPlayerInfoList();
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  com.sky9th.game.chat.protos.PlayerInfo getPlayerInfo(int index);
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  int getPlayerInfoCount();
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  java.util.List<? extends com.sky9th.game.chat.protos.PlayerInfoOrBuilder> 
      getPlayerInfoOrBuilderList();
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  com.sky9th.game.chat.protos.PlayerInfoOrBuilder getPlayerInfoOrBuilder(
      int index);
}
