// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerList.proto

package com.sky9th.game.chat.protos;

public final class PlayerListProtos {
  private PlayerListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sky9th_Protobuf_PlayerList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sky9th_Protobuf_PlayerList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PlayerList.proto\022\017Sky9th.Protobuf\032\020Pla" +
      "yerInfo.proto\"W\n\nPlayerList\022\030\n\004type\030\002 \001(" +
      "\t:\nPlayerList\022/\n\nplayerInfo\030\003 \003(\0132\033.Sky9" +
      "th.Protobuf.PlayerInfoB1\n\033com.sky9th.gam" +
      "e.chat.protosB\020PlayerListProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sky9th.game.chat.protos.PlayerInfoProtos.getDescriptor(),
        });
    internal_static_Sky9th_Protobuf_PlayerList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sky9th_Protobuf_PlayerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sky9th_Protobuf_PlayerList_descriptor,
        new java.lang.String[] { "Type", "PlayerInfo", });
    com.sky9th.game.chat.protos.PlayerInfoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
