// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.protos;

/**
 * Protobuf type {@code Sky9th.Protobuf.PlayerInfo}
 */
public final class PlayerInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Sky9th.Protobuf.PlayerInfo)
    PlayerInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerInfo.newBuilder() to construct.
  private PlayerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerInfo() {
    networkID_ = "";
    type_ = "PlayerInfo";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sky9th.game.chat.protos.PlayerInfoProtos.internal_static_Sky9th_Protobuf_PlayerInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sky9th.game.chat.protos.PlayerInfoProtos.internal_static_Sky9th_Protobuf_PlayerInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sky9th.game.chat.protos.PlayerInfo.class, com.sky9th.game.chat.protos.PlayerInfo.Builder.class);
  }

  private int bitField0_;
  public static final int NETWORKID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object networkID_ = "";
  /**
   * <code>required string networkID = 1;</code>
   * @return Whether the networkID field is set.
   */
  @java.lang.Override
  public boolean hasNetworkID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string networkID = 1;</code>
   * @return The networkID.
   */
  @java.lang.Override
  public java.lang.String getNetworkID() {
    java.lang.Object ref = networkID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        networkID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkIDBytes() {
    java.lang.Object ref = networkID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "PlayerInfo";
  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        type_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFORM_FIELD_NUMBER = 3;
  private com.sky9th.game.chat.protos.Transform transform_;
  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   * @return Whether the transform field is set.
   */
  @java.lang.Override
  public boolean hasTransform() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   * @return The transform.
   */
  @java.lang.Override
  public com.sky9th.game.chat.protos.Transform getTransform() {
    return transform_ == null ? com.sky9th.game.chat.protos.Transform.getDefaultInstance() : transform_;
  }
  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   */
  @java.lang.Override
  public com.sky9th.game.chat.protos.TransformOrBuilder getTransformOrBuilder() {
    return transform_ == null ? com.sky9th.game.chat.protos.Transform.getDefaultInstance() : transform_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasNetworkID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTransform()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getTransform().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, networkID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getTransform());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, networkID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTransform());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sky9th.game.chat.protos.PlayerInfo)) {
      return super.equals(obj);
    }
    com.sky9th.game.chat.protos.PlayerInfo other = (com.sky9th.game.chat.protos.PlayerInfo) obj;

    if (hasNetworkID() != other.hasNetworkID()) return false;
    if (hasNetworkID()) {
      if (!getNetworkID()
          .equals(other.getNetworkID())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (hasTransform() != other.hasTransform()) return false;
    if (hasTransform()) {
      if (!getTransform()
          .equals(other.getTransform())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNetworkID()) {
      hash = (37 * hash) + NETWORKID_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkID().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (hasTransform()) {
      hash = (37 * hash) + TRANSFORM_FIELD_NUMBER;
      hash = (53 * hash) + getTransform().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sky9th.game.chat.protos.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sky9th.game.chat.protos.PlayerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.protos.PlayerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sky9th.game.chat.protos.PlayerInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Sky9th.Protobuf.PlayerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Sky9th.Protobuf.PlayerInfo)
      com.sky9th.game.chat.protos.PlayerInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky9th.game.chat.protos.PlayerInfoProtos.internal_static_Sky9th_Protobuf_PlayerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky9th.game.chat.protos.PlayerInfoProtos.internal_static_Sky9th_Protobuf_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky9th.game.chat.protos.PlayerInfo.class, com.sky9th.game.chat.protos.PlayerInfo.Builder.class);
    }

    // Construct using com.sky9th.game.chat.protos.PlayerInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransformFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      networkID_ = "";
      type_ = "PlayerInfo";
      transform_ = null;
      if (transformBuilder_ != null) {
        transformBuilder_.dispose();
        transformBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sky9th.game.chat.protos.PlayerInfoProtos.internal_static_Sky9th_Protobuf_PlayerInfo_descriptor;
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerInfo getDefaultInstanceForType() {
      return com.sky9th.game.chat.protos.PlayerInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerInfo build() {
      com.sky9th.game.chat.protos.PlayerInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerInfo buildPartial() {
      com.sky9th.game.chat.protos.PlayerInfo result = new com.sky9th.game.chat.protos.PlayerInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sky9th.game.chat.protos.PlayerInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.networkID_ = networkID_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.transform_ = transformBuilder_ == null
            ? transform_
            : transformBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sky9th.game.chat.protos.PlayerInfo) {
        return mergeFrom((com.sky9th.game.chat.protos.PlayerInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sky9th.game.chat.protos.PlayerInfo other) {
      if (other == com.sky9th.game.chat.protos.PlayerInfo.getDefaultInstance()) return this;
      if (other.hasNetworkID()) {
        networkID_ = other.networkID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasType()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasTransform()) {
        mergeTransform(other.getTransform());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasNetworkID()) {
        return false;
      }
      if (!hasType()) {
        return false;
      }
      if (!hasTransform()) {
        return false;
      }
      if (!getTransform().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              networkID_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTransformFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object networkID_ = "";
    /**
     * <code>required string networkID = 1;</code>
     * @return Whether the networkID field is set.
     */
    public boolean hasNetworkID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return The networkID.
     */
    public java.lang.String getNetworkID() {
      java.lang.Object ref = networkID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          networkID_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return The bytes for networkID.
     */
    public com.google.protobuf.ByteString
        getNetworkIDBytes() {
      java.lang.Object ref = networkID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string networkID = 1;</code>
     * @param value The networkID to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      networkID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkID() {
      networkID_ = getDefaultInstance().getNetworkID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string networkID = 1;</code>
     * @param value The bytes for networkID to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      networkID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "PlayerInfo";
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 2 [default = "PlayerInfo"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.sky9th.game.chat.protos.Transform transform_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sky9th.game.chat.protos.Transform, com.sky9th.game.chat.protos.Transform.Builder, com.sky9th.game.chat.protos.TransformOrBuilder> transformBuilder_;
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     * @return Whether the transform field is set.
     */
    public boolean hasTransform() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     * @return The transform.
     */
    public com.sky9th.game.chat.protos.Transform getTransform() {
      if (transformBuilder_ == null) {
        return transform_ == null ? com.sky9th.game.chat.protos.Transform.getDefaultInstance() : transform_;
      } else {
        return transformBuilder_.getMessage();
      }
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public Builder setTransform(com.sky9th.game.chat.protos.Transform value) {
      if (transformBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transform_ = value;
      } else {
        transformBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public Builder setTransform(
        com.sky9th.game.chat.protos.Transform.Builder builderForValue) {
      if (transformBuilder_ == null) {
        transform_ = builderForValue.build();
      } else {
        transformBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public Builder mergeTransform(com.sky9th.game.chat.protos.Transform value) {
      if (transformBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          transform_ != null &&
          transform_ != com.sky9th.game.chat.protos.Transform.getDefaultInstance()) {
          getTransformBuilder().mergeFrom(value);
        } else {
          transform_ = value;
        }
      } else {
        transformBuilder_.mergeFrom(value);
      }
      if (transform_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public Builder clearTransform() {
      bitField0_ = (bitField0_ & ~0x00000004);
      transform_ = null;
      if (transformBuilder_ != null) {
        transformBuilder_.dispose();
        transformBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public com.sky9th.game.chat.protos.Transform.Builder getTransformBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTransformFieldBuilder().getBuilder();
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    public com.sky9th.game.chat.protos.TransformOrBuilder getTransformOrBuilder() {
      if (transformBuilder_ != null) {
        return transformBuilder_.getMessageOrBuilder();
      } else {
        return transform_ == null ?
            com.sky9th.game.chat.protos.Transform.getDefaultInstance() : transform_;
      }
    }
    /**
     * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sky9th.game.chat.protos.Transform, com.sky9th.game.chat.protos.Transform.Builder, com.sky9th.game.chat.protos.TransformOrBuilder> 
        getTransformFieldBuilder() {
      if (transformBuilder_ == null) {
        transformBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sky9th.game.chat.protos.Transform, com.sky9th.game.chat.protos.Transform.Builder, com.sky9th.game.chat.protos.TransformOrBuilder>(
                getTransform(),
                getParentForChildren(),
                isClean());
        transform_ = null;
      }
      return transformBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Sky9th.Protobuf.PlayerInfo)
  }

  // @@protoc_insertion_point(class_scope:Sky9th.Protobuf.PlayerInfo)
  private static final com.sky9th.game.chat.protos.PlayerInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sky9th.game.chat.protos.PlayerInfo();
  }

  public static com.sky9th.game.chat.protos.PlayerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerInfo>
      PARSER = new com.google.protobuf.AbstractParser<PlayerInfo>() {
    @java.lang.Override
    public PlayerInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sky9th.game.chat.protos.PlayerInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

