// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.protos;

public interface PlayerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.PlayerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string networkID = 1;</code>
   * @return The networkID.
   */
  java.lang.String getNetworkID();
  /**
   * <code>string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  com.google.protobuf.ByteString
      getNetworkIDBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.Sky9th.Protobuf.Transform transform = 3;</code>
   * @return Whether the transform field is set.
   */
  boolean hasTransform();
  /**
   * <code>.Sky9th.Protobuf.Transform transform = 3;</code>
   * @return The transform.
   */
  com.sky9th.game.chat.protos.Transform getTransform();
  /**
   * <code>.Sky9th.Protobuf.Transform transform = 3;</code>
   */
  com.sky9th.game.chat.protos.TransformOrBuilder getTransformOrBuilder();
}
