// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerList.proto

package com.sky9th.game.chat.protos;

/**
 * Protobuf type {@code Sky9th.Protobuf.PlayerList}
 */
public final class PlayerList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Sky9th.Protobuf.PlayerList)
    PlayerListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayerList.newBuilder() to construct.
  private PlayerList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayerList() {
    type_ = "PlayerList";
    playerInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayerList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sky9th.game.chat.protos.PlayerListProtos.internal_static_Sky9th_Protobuf_PlayerList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sky9th.game.chat.protos.PlayerListProtos.internal_static_Sky9th_Protobuf_PlayerList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sky9th.game.chat.protos.PlayerList.class, com.sky9th.game.chat.protos.PlayerList.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "PlayerList";
  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        type_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string type = 1 [default = "PlayerList"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERINFO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.sky9th.game.chat.protos.PlayerInfo> playerInfo_;
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.sky9th.game.chat.protos.PlayerInfo> getPlayerInfoList() {
    return playerInfo_;
  }
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sky9th.game.chat.protos.PlayerInfoOrBuilder> 
      getPlayerInfoOrBuilderList() {
    return playerInfo_;
  }
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  @java.lang.Override
  public int getPlayerInfoCount() {
    return playerInfo_.size();
  }
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  @java.lang.Override
  public com.sky9th.game.chat.protos.PlayerInfo getPlayerInfo(int index) {
    return playerInfo_.get(index);
  }
  /**
   * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
   */
  @java.lang.Override
  public com.sky9th.game.chat.protos.PlayerInfoOrBuilder getPlayerInfoOrBuilder(
      int index) {
    return playerInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getPlayerInfoCount(); i++) {
      if (!getPlayerInfo(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    for (int i = 0; i < playerInfo_.size(); i++) {
      output.writeMessage(2, playerInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    for (int i = 0; i < playerInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, playerInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sky9th.game.chat.protos.PlayerList)) {
      return super.equals(obj);
    }
    com.sky9th.game.chat.protos.PlayerList other = (com.sky9th.game.chat.protos.PlayerList) obj;

    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (!getPlayerInfoList()
        .equals(other.getPlayerInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (getPlayerInfoCount() > 0) {
      hash = (37 * hash) + PLAYERINFO_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sky9th.game.chat.protos.PlayerList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sky9th.game.chat.protos.PlayerList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.protos.PlayerList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sky9th.game.chat.protos.PlayerList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Sky9th.Protobuf.PlayerList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Sky9th.Protobuf.PlayerList)
      com.sky9th.game.chat.protos.PlayerListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky9th.game.chat.protos.PlayerListProtos.internal_static_Sky9th_Protobuf_PlayerList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky9th.game.chat.protos.PlayerListProtos.internal_static_Sky9th_Protobuf_PlayerList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky9th.game.chat.protos.PlayerList.class, com.sky9th.game.chat.protos.PlayerList.Builder.class);
    }

    // Construct using com.sky9th.game.chat.protos.PlayerList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = "PlayerList";
      if (playerInfoBuilder_ == null) {
        playerInfo_ = java.util.Collections.emptyList();
      } else {
        playerInfo_ = null;
        playerInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sky9th.game.chat.protos.PlayerListProtos.internal_static_Sky9th_Protobuf_PlayerList_descriptor;
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerList getDefaultInstanceForType() {
      return com.sky9th.game.chat.protos.PlayerList.getDefaultInstance();
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerList build() {
      com.sky9th.game.chat.protos.PlayerList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sky9th.game.chat.protos.PlayerList buildPartial() {
      com.sky9th.game.chat.protos.PlayerList result = new com.sky9th.game.chat.protos.PlayerList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.sky9th.game.chat.protos.PlayerList result) {
      if (playerInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          playerInfo_ = java.util.Collections.unmodifiableList(playerInfo_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.playerInfo_ = playerInfo_;
      } else {
        result.playerInfo_ = playerInfoBuilder_.build();
      }
    }

    private void buildPartial0(com.sky9th.game.chat.protos.PlayerList result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sky9th.game.chat.protos.PlayerList) {
        return mergeFrom((com.sky9th.game.chat.protos.PlayerList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sky9th.game.chat.protos.PlayerList other) {
      if (other == com.sky9th.game.chat.protos.PlayerList.getDefaultInstance()) return this;
      if (other.hasType()) {
        type_ = other.type_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (playerInfoBuilder_ == null) {
        if (!other.playerInfo_.isEmpty()) {
          if (playerInfo_.isEmpty()) {
            playerInfo_ = other.playerInfo_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePlayerInfoIsMutable();
            playerInfo_.addAll(other.playerInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.playerInfo_.isEmpty()) {
          if (playerInfoBuilder_.isEmpty()) {
            playerInfoBuilder_.dispose();
            playerInfoBuilder_ = null;
            playerInfo_ = other.playerInfo_;
            bitField0_ = (bitField0_ & ~0x00000002);
            playerInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayerInfoFieldBuilder() : null;
          } else {
            playerInfoBuilder_.addAllMessages(other.playerInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getPlayerInfoCount(); i++) {
        if (!getPlayerInfo(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              type_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.sky9th.game.chat.protos.PlayerInfo m =
                  input.readMessage(
                      com.sky9th.game.chat.protos.PlayerInfo.PARSER,
                      extensionRegistry);
              if (playerInfoBuilder_ == null) {
                ensurePlayerInfoIsMutable();
                playerInfo_.add(m);
              } else {
                playerInfoBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "PlayerList";
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1 [default = "PlayerList"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.sky9th.game.chat.protos.PlayerInfo> playerInfo_ =
      java.util.Collections.emptyList();
    private void ensurePlayerInfoIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        playerInfo_ = new java.util.ArrayList<com.sky9th.game.chat.protos.PlayerInfo>(playerInfo_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sky9th.game.chat.protos.PlayerInfo, com.sky9th.game.chat.protos.PlayerInfo.Builder, com.sky9th.game.chat.protos.PlayerInfoOrBuilder> playerInfoBuilder_;

    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public java.util.List<com.sky9th.game.chat.protos.PlayerInfo> getPlayerInfoList() {
      if (playerInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(playerInfo_);
      } else {
        return playerInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public int getPlayerInfoCount() {
      if (playerInfoBuilder_ == null) {
        return playerInfo_.size();
      } else {
        return playerInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public com.sky9th.game.chat.protos.PlayerInfo getPlayerInfo(int index) {
      if (playerInfoBuilder_ == null) {
        return playerInfo_.get(index);
      } else {
        return playerInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder setPlayerInfo(
        int index, com.sky9th.game.chat.protos.PlayerInfo value) {
      if (playerInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerInfoIsMutable();
        playerInfo_.set(index, value);
        onChanged();
      } else {
        playerInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder setPlayerInfo(
        int index, com.sky9th.game.chat.protos.PlayerInfo.Builder builderForValue) {
      if (playerInfoBuilder_ == null) {
        ensurePlayerInfoIsMutable();
        playerInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        playerInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder addPlayerInfo(com.sky9th.game.chat.protos.PlayerInfo value) {
      if (playerInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerInfoIsMutable();
        playerInfo_.add(value);
        onChanged();
      } else {
        playerInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder addPlayerInfo(
        int index, com.sky9th.game.chat.protos.PlayerInfo value) {
      if (playerInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerInfoIsMutable();
        playerInfo_.add(index, value);
        onChanged();
      } else {
        playerInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder addPlayerInfo(
        com.sky9th.game.chat.protos.PlayerInfo.Builder builderForValue) {
      if (playerInfoBuilder_ == null) {
        ensurePlayerInfoIsMutable();
        playerInfo_.add(builderForValue.build());
        onChanged();
      } else {
        playerInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder addPlayerInfo(
        int index, com.sky9th.game.chat.protos.PlayerInfo.Builder builderForValue) {
      if (playerInfoBuilder_ == null) {
        ensurePlayerInfoIsMutable();
        playerInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        playerInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder addAllPlayerInfo(
        java.lang.Iterable<? extends com.sky9th.game.chat.protos.PlayerInfo> values) {
      if (playerInfoBuilder_ == null) {
        ensurePlayerInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, playerInfo_);
        onChanged();
      } else {
        playerInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder clearPlayerInfo() {
      if (playerInfoBuilder_ == null) {
        playerInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        playerInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public Builder removePlayerInfo(int index) {
      if (playerInfoBuilder_ == null) {
        ensurePlayerInfoIsMutable();
        playerInfo_.remove(index);
        onChanged();
      } else {
        playerInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public com.sky9th.game.chat.protos.PlayerInfo.Builder getPlayerInfoBuilder(
        int index) {
      return getPlayerInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public com.sky9th.game.chat.protos.PlayerInfoOrBuilder getPlayerInfoOrBuilder(
        int index) {
      if (playerInfoBuilder_ == null) {
        return playerInfo_.get(index);  } else {
        return playerInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public java.util.List<? extends com.sky9th.game.chat.protos.PlayerInfoOrBuilder> 
         getPlayerInfoOrBuilderList() {
      if (playerInfoBuilder_ != null) {
        return playerInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(playerInfo_);
      }
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public com.sky9th.game.chat.protos.PlayerInfo.Builder addPlayerInfoBuilder() {
      return getPlayerInfoFieldBuilder().addBuilder(
          com.sky9th.game.chat.protos.PlayerInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public com.sky9th.game.chat.protos.PlayerInfo.Builder addPlayerInfoBuilder(
        int index) {
      return getPlayerInfoFieldBuilder().addBuilder(
          index, com.sky9th.game.chat.protos.PlayerInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Sky9th.Protobuf.PlayerInfo playerInfo = 2;</code>
     */
    public java.util.List<com.sky9th.game.chat.protos.PlayerInfo.Builder> 
         getPlayerInfoBuilderList() {
      return getPlayerInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sky9th.game.chat.protos.PlayerInfo, com.sky9th.game.chat.protos.PlayerInfo.Builder, com.sky9th.game.chat.protos.PlayerInfoOrBuilder> 
        getPlayerInfoFieldBuilder() {
      if (playerInfoBuilder_ == null) {
        playerInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sky9th.game.chat.protos.PlayerInfo, com.sky9th.game.chat.protos.PlayerInfo.Builder, com.sky9th.game.chat.protos.PlayerInfoOrBuilder>(
                playerInfo_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        playerInfo_ = null;
      }
      return playerInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Sky9th.Protobuf.PlayerList)
  }

  // @@protoc_insertion_point(class_scope:Sky9th.Protobuf.PlayerList)
  private static final com.sky9th.game.chat.protos.PlayerList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sky9th.game.chat.protos.PlayerList();
  }

  public static com.sky9th.game.chat.protos.PlayerList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerList>
      PARSER = new com.google.protobuf.AbstractParser<PlayerList>() {
    @java.lang.Override
    public PlayerList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sky9th.game.chat.protos.PlayerList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

