// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.protos;

public interface TransformOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Transform)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3;</code>
   * @return The z.
   */
  double getZ();
}
