// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.protos;

public interface TransformOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Transform)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required double x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>required double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>required double y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>required double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>required double z = 3;</code>
   * @return Whether the z field is set.
   */
  boolean hasZ();
  /**
   * <code>required double z = 3;</code>
   * @return The z.
   */
  double getZ();
}
