// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.sky9th.game.chat.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string networkID = 1;</code>
   * @return Whether the networkID field is set.
   */
  boolean hasNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The networkID.
   */
  java.lang.String getNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  com.google.protobuf.ByteString
      getNetworkIDBytes();

  /**
   * <code>required string type = 2 [default = "Message"];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 2 [default = "Message"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 2 [default = "Message"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>required string message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>required string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
