// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.proto;

public interface PlayerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.PlayerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string networkID = 1;</code>
   * @return Whether the networkID field is set.
   */
  boolean hasNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The networkID.
   */
  java.lang.String getNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  com.google.protobuf.ByteString
      getNetworkIDBytes();

  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 2 [default = "PlayerInfo"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   * @return Whether the transform field is set.
   */
  boolean hasTransform();
  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   * @return The transform.
   */
  com.sky9th.game.chat.proto.Transform getTransform();
  /**
   * <code>required .Sky9th.Protobuf.Transform transform = 3;</code>
   */
  com.sky9th.game.chat.proto.TransformOrBuilder getTransformOrBuilder();
}
