// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Respawn.proto

package com.sky9th.game.chat.proto;

/**
 * Protobuf type {@code Sky9th.Protobuf.Respawn}
 */
public final class Respawn extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Sky9th.Protobuf.Respawn)
    RespawnOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Respawn.newBuilder() to construct.
  private Respawn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Respawn() {
    networkID_ = "";
    type_ = "Respawn";
    respawnType_ = 1;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Respawn();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sky9th.game.chat.proto.RespawnProto.internal_static_Sky9th_Protobuf_Respawn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sky9th.game.chat.proto.RespawnProto.internal_static_Sky9th_Protobuf_Respawn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sky9th.game.chat.proto.Respawn.class, com.sky9th.game.chat.proto.Respawn.Builder.class);
  }

  private int bitField0_;
  public static final int NETWORKID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object networkID_ = "";
  /**
   * <code>required string networkID = 1;</code>
   * @return Whether the networkID field is set.
   */
  @java.lang.Override
  public boolean hasNetworkID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string networkID = 1;</code>
   * @return The networkID.
   */
  @java.lang.Override
  public java.lang.String getNetworkID() {
    java.lang.Object ref = networkID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        networkID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkIDBytes() {
    java.lang.Object ref = networkID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "Respawn";
  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        type_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPAWNTYPE_FIELD_NUMBER = 3;
  private int respawnType_ = 1;
  /**
   * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
   * @return Whether the respawnType field is set.
   */
  @java.lang.Override public boolean hasRespawnType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
   * @return The respawnType.
   */
  @java.lang.Override public com.sky9th.game.chat.proto.RespawnType getRespawnType() {
    com.sky9th.game.chat.proto.RespawnType result = com.sky9th.game.chat.proto.RespawnType.forNumber(respawnType_);
    return result == null ? com.sky9th.game.chat.proto.RespawnType.Player : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasNetworkID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRespawnType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, networkID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, respawnType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, networkID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, respawnType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sky9th.game.chat.proto.Respawn)) {
      return super.equals(obj);
    }
    com.sky9th.game.chat.proto.Respawn other = (com.sky9th.game.chat.proto.Respawn) obj;

    if (hasNetworkID() != other.hasNetworkID()) return false;
    if (hasNetworkID()) {
      if (!getNetworkID()
          .equals(other.getNetworkID())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (hasRespawnType() != other.hasRespawnType()) return false;
    if (hasRespawnType()) {
      if (respawnType_ != other.respawnType_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNetworkID()) {
      hash = (37 * hash) + NETWORKID_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkID().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (hasRespawnType()) {
      hash = (37 * hash) + RESPAWNTYPE_FIELD_NUMBER;
      hash = (53 * hash) + respawnType_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sky9th.game.chat.proto.Respawn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sky9th.game.chat.proto.Respawn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.proto.Respawn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sky9th.game.chat.proto.Respawn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Sky9th.Protobuf.Respawn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Sky9th.Protobuf.Respawn)
      com.sky9th.game.chat.proto.RespawnOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky9th.game.chat.proto.RespawnProto.internal_static_Sky9th_Protobuf_Respawn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky9th.game.chat.proto.RespawnProto.internal_static_Sky9th_Protobuf_Respawn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky9th.game.chat.proto.Respawn.class, com.sky9th.game.chat.proto.Respawn.Builder.class);
    }

    // Construct using com.sky9th.game.chat.proto.Respawn.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      networkID_ = "";
      type_ = "Respawn";
      respawnType_ = 1;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sky9th.game.chat.proto.RespawnProto.internal_static_Sky9th_Protobuf_Respawn_descriptor;
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Respawn getDefaultInstanceForType() {
      return com.sky9th.game.chat.proto.Respawn.getDefaultInstance();
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Respawn build() {
      com.sky9th.game.chat.proto.Respawn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Respawn buildPartial() {
      com.sky9th.game.chat.proto.Respawn result = new com.sky9th.game.chat.proto.Respawn(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sky9th.game.chat.proto.Respawn result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.networkID_ = networkID_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.respawnType_ = respawnType_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sky9th.game.chat.proto.Respawn) {
        return mergeFrom((com.sky9th.game.chat.proto.Respawn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sky9th.game.chat.proto.Respawn other) {
      if (other == com.sky9th.game.chat.proto.Respawn.getDefaultInstance()) return this;
      if (other.hasNetworkID()) {
        networkID_ = other.networkID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasType()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasRespawnType()) {
        setRespawnType(other.getRespawnType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasNetworkID()) {
        return false;
      }
      if (!hasType()) {
        return false;
      }
      if (!hasRespawnType()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              networkID_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              int tmpRaw = input.readEnum();
              com.sky9th.game.chat.proto.RespawnType tmpValue =
                  com.sky9th.game.chat.proto.RespawnType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(3, tmpRaw);
              } else {
                respawnType_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object networkID_ = "";
    /**
     * <code>required string networkID = 1;</code>
     * @return Whether the networkID field is set.
     */
    public boolean hasNetworkID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return The networkID.
     */
    public java.lang.String getNetworkID() {
      java.lang.Object ref = networkID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          networkID_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return The bytes for networkID.
     */
    public com.google.protobuf.ByteString
        getNetworkIDBytes() {
      java.lang.Object ref = networkID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string networkID = 1;</code>
     * @param value The networkID to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      networkID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string networkID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkID() {
      networkID_ = getDefaultInstance().getNetworkID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string networkID = 1;</code>
     * @param value The bytes for networkID to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      networkID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "Respawn";
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 2 [default = "Respawn"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int respawnType_ = 1;
    /**
     * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
     * @return Whether the respawnType field is set.
     */
    @java.lang.Override public boolean hasRespawnType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
     * @return The respawnType.
     */
    @java.lang.Override
    public com.sky9th.game.chat.proto.RespawnType getRespawnType() {
      com.sky9th.game.chat.proto.RespawnType result = com.sky9th.game.chat.proto.RespawnType.forNumber(respawnType_);
      return result == null ? com.sky9th.game.chat.proto.RespawnType.Player : result;
    }
    /**
     * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
     * @param value The respawnType to set.
     * @return This builder for chaining.
     */
    public Builder setRespawnType(com.sky9th.game.chat.proto.RespawnType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      respawnType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRespawnType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      respawnType_ = 1;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Sky9th.Protobuf.Respawn)
  }

  // @@protoc_insertion_point(class_scope:Sky9th.Protobuf.Respawn)
  private static final com.sky9th.game.chat.proto.Respawn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sky9th.game.chat.proto.Respawn();
  }

  public static com.sky9th.game.chat.proto.Respawn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Respawn>
      PARSER = new com.google.protobuf.AbstractParser<Respawn>() {
    @java.lang.Override
    public Respawn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Respawn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Respawn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sky9th.game.chat.proto.Respawn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

