// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Respawn.proto

package com.sky9th.game.chat.proto;

/**
 * Protobuf enum {@code Sky9th.Protobuf.RespawnType}
 */
public enum RespawnType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Player = 1;</code>
   */
  Player(1),
  ;

  /**
   * <code>Player = 1;</code>
   */
  public static final int Player_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RespawnType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RespawnType forNumber(int value) {
    switch (value) {
      case 1: return Player;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RespawnType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RespawnType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RespawnType>() {
          public RespawnType findValueByNumber(int number) {
            return RespawnType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sky9th.game.chat.proto.RespawnProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RespawnType[] VALUES = values();

  public static RespawnType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RespawnType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Sky9th.Protobuf.RespawnType)
}

