// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Respawn.proto

package com.sky9th.game.chat.proto;

public final class RespawnProto {
  private RespawnProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sky9th_Protobuf_Respawn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sky9th_Protobuf_Respawn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRespawn.proto\022\017Sky9th.Protobuf\"f\n\007Resp" +
      "awn\022\021\n\tnetworkID\030\001 \002(\t\022\025\n\004type\030\002 \002(\t:\007Re" +
      "spawn\0221\n\013respawnType\030\003 \002(\0162\034.Sky9th.Prot" +
      "obuf.RespawnType*\031\n\013RespawnType\022\n\n\006Playe" +
      "r\020\001B,\n\032com.sky9th.game.chat.protoB\014Respa" +
      "wnProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Sky9th_Protobuf_Respawn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sky9th_Protobuf_Respawn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sky9th_Protobuf_Respawn_descriptor,
        new java.lang.String[] { "NetworkID", "Type", "RespawnType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
