// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Respawn.proto

package com.sky9th.game.chat.proto;

public interface RespawnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Respawn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string networkID = 1;</code>
   * @return Whether the networkID field is set.
   */
  boolean hasNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The networkID.
   */
  java.lang.String getNetworkID();
  /**
   * <code>required string networkID = 1;</code>
   * @return The bytes for networkID.
   */
  com.google.protobuf.ByteString
      getNetworkIDBytes();

  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>required string type = 2 [default = "Respawn"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
   * @return Whether the respawnType field is set.
   */
  boolean hasRespawnType();
  /**
   * <code>required .Sky9th.Protobuf.RespawnType respawnType = 3;</code>
   * @return The respawnType.
   */
  com.sky9th.game.chat.proto.RespawnType getRespawnType();
}
