// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.proto;

public interface TransformOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sky9th.Protobuf.Transform)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required double x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>required double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>required double y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>required double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>required double z = 3;</code>
   * @return Whether the z field is set.
   */
  boolean hasZ();
  /**
   * <code>required double z = 3;</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>required bool up = 4;</code>
   * @return Whether the up field is set.
   */
  boolean hasUp();
  /**
   * <code>required bool up = 4;</code>
   * @return The up.
   */
  boolean getUp();

  /**
   * <code>required bool down = 5;</code>
   * @return Whether the down field is set.
   */
  boolean hasDown();
  /**
   * <code>required bool down = 5;</code>
   * @return The down.
   */
  boolean getDown();

  /**
   * <code>required bool left = 6;</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>required bool left = 6;</code>
   * @return The left.
   */
  boolean getLeft();

  /**
   * <code>required bool right = 7;</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>required bool right = 7;</code>
   * @return The right.
   */
  boolean getRight();
}
