// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.sky9th.game.chat.proto;

/**
 * Protobuf type {@code Sky9th.Protobuf.Transform}
 */
public final class Transform extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Sky9th.Protobuf.Transform)
    TransformOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Transform.newBuilder() to construct.
  private Transform(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Transform() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Transform();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sky9th.game.chat.proto.PlayerInfoProto.internal_static_Sky9th_Protobuf_Transform_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sky9th.game.chat.proto.PlayerInfoProto.internal_static_Sky9th_Protobuf_Transform_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sky9th.game.chat.proto.Transform.class, com.sky9th.game.chat.proto.Transform.Builder.class);
  }

  private int bitField0_;
  public static final int X_FIELD_NUMBER = 1;
  private double x_ = 0D;
  /**
   * <code>required double x = 1;</code>
   * @return Whether the x field is set.
   */
  @java.lang.Override
  public boolean hasX() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required double x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public double getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private double y_ = 0D;
  /**
   * <code>required double y = 2;</code>
   * @return Whether the y field is set.
   */
  @java.lang.Override
  public boolean hasY() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required double y = 2;</code>
   * @return The y.
   */
  @java.lang.Override
  public double getY() {
    return y_;
  }

  public static final int Z_FIELD_NUMBER = 3;
  private double z_ = 0D;
  /**
   * <code>required double z = 3;</code>
   * @return Whether the z field is set.
   */
  @java.lang.Override
  public boolean hasZ() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required double z = 3;</code>
   * @return The z.
   */
  @java.lang.Override
  public double getZ() {
    return z_;
  }

  public static final int UP_FIELD_NUMBER = 4;
  private boolean up_ = false;
  /**
   * <code>required bool up = 4;</code>
   * @return Whether the up field is set.
   */
  @java.lang.Override
  public boolean hasUp() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required bool up = 4;</code>
   * @return The up.
   */
  @java.lang.Override
  public boolean getUp() {
    return up_;
  }

  public static final int DOWN_FIELD_NUMBER = 5;
  private boolean down_ = false;
  /**
   * <code>required bool down = 5;</code>
   * @return Whether the down field is set.
   */
  @java.lang.Override
  public boolean hasDown() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required bool down = 5;</code>
   * @return The down.
   */
  @java.lang.Override
  public boolean getDown() {
    return down_;
  }

  public static final int LEFT_FIELD_NUMBER = 6;
  private boolean left_ = false;
  /**
   * <code>required bool left = 6;</code>
   * @return Whether the left field is set.
   */
  @java.lang.Override
  public boolean hasLeft() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required bool left = 6;</code>
   * @return The left.
   */
  @java.lang.Override
  public boolean getLeft() {
    return left_;
  }

  public static final int RIGHT_FIELD_NUMBER = 7;
  private boolean right_ = false;
  /**
   * <code>required bool right = 7;</code>
   * @return Whether the right field is set.
   */
  @java.lang.Override
  public boolean hasRight() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>required bool right = 7;</code>
   * @return The right.
   */
  @java.lang.Override
  public boolean getRight() {
    return right_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasX()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasZ()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasUp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDown()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLeft()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRight()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeDouble(1, x_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(2, y_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(3, z_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(4, up_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBool(5, down_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBool(6, left_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeBool(7, right_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, x_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, y_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, z_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, up_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, down_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, left_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, right_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sky9th.game.chat.proto.Transform)) {
      return super.equals(obj);
    }
    com.sky9th.game.chat.proto.Transform other = (com.sky9th.game.chat.proto.Transform) obj;

    if (hasX() != other.hasX()) return false;
    if (hasX()) {
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
    }
    if (hasY() != other.hasY()) return false;
    if (hasY()) {
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
    }
    if (hasZ() != other.hasZ()) return false;
    if (hasZ()) {
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
    }
    if (hasUp() != other.hasUp()) return false;
    if (hasUp()) {
      if (getUp()
          != other.getUp()) return false;
    }
    if (hasDown() != other.hasDown()) return false;
    if (hasDown()) {
      if (getDown()
          != other.getDown()) return false;
    }
    if (hasLeft() != other.hasLeft()) return false;
    if (hasLeft()) {
      if (getLeft()
          != other.getLeft()) return false;
    }
    if (hasRight() != other.hasRight()) return false;
    if (hasRight()) {
      if (getRight()
          != other.getRight()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasX()) {
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
    }
    if (hasY()) {
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
    }
    if (hasZ()) {
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
    }
    if (hasUp()) {
      hash = (37 * hash) + UP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUp());
    }
    if (hasDown()) {
      hash = (37 * hash) + DOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDown());
    }
    if (hasLeft()) {
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLeft());
    }
    if (hasRight()) {
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRight());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sky9th.game.chat.proto.Transform parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sky9th.game.chat.proto.Transform parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sky9th.game.chat.proto.Transform parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sky9th.game.chat.proto.Transform parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sky9th.game.chat.proto.Transform prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Sky9th.Protobuf.Transform}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Sky9th.Protobuf.Transform)
      com.sky9th.game.chat.proto.TransformOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sky9th.game.chat.proto.PlayerInfoProto.internal_static_Sky9th_Protobuf_Transform_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sky9th.game.chat.proto.PlayerInfoProto.internal_static_Sky9th_Protobuf_Transform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sky9th.game.chat.proto.Transform.class, com.sky9th.game.chat.proto.Transform.Builder.class);
    }

    // Construct using com.sky9th.game.chat.proto.Transform.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
      up_ = false;
      down_ = false;
      left_ = false;
      right_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sky9th.game.chat.proto.PlayerInfoProto.internal_static_Sky9th_Protobuf_Transform_descriptor;
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Transform getDefaultInstanceForType() {
      return com.sky9th.game.chat.proto.Transform.getDefaultInstance();
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Transform build() {
      com.sky9th.game.chat.proto.Transform result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sky9th.game.chat.proto.Transform buildPartial() {
      com.sky9th.game.chat.proto.Transform result = new com.sky9th.game.chat.proto.Transform(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sky9th.game.chat.proto.Transform result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x_ = x_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.y_ = y_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.z_ = z_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.up_ = up_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.down_ = down_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.left_ = left_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.right_ = right_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sky9th.game.chat.proto.Transform) {
        return mergeFrom((com.sky9th.game.chat.proto.Transform)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sky9th.game.chat.proto.Transform other) {
      if (other == com.sky9th.game.chat.proto.Transform.getDefaultInstance()) return this;
      if (other.hasX()) {
        setX(other.getX());
      }
      if (other.hasY()) {
        setY(other.getY());
      }
      if (other.hasZ()) {
        setZ(other.getZ());
      }
      if (other.hasUp()) {
        setUp(other.getUp());
      }
      if (other.hasDown()) {
        setDown(other.getDown());
      }
      if (other.hasLeft()) {
        setLeft(other.getLeft());
      }
      if (other.hasRight()) {
        setRight(other.getRight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasX()) {
        return false;
      }
      if (!hasY()) {
        return false;
      }
      if (!hasZ()) {
        return false;
      }
      if (!hasUp()) {
        return false;
      }
      if (!hasDown()) {
        return false;
      }
      if (!hasLeft()) {
        return false;
      }
      if (!hasRight()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              x_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              y_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              z_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 32: {
              up_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              down_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              left_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              right_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double x_ ;
    /**
     * <code>required double x = 1;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }
    /**
     * <code>required double x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(double value) {

      x_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required double x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0D;
      onChanged();
      return this;
    }

    private double y_ ;
    /**
     * <code>required double y = 2;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }
    /**
     * <code>required double y = 2;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(double value) {

      y_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required double y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0D;
      onChanged();
      return this;
    }

    private double z_ ;
    /**
     * <code>required double z = 3;</code>
     * @return Whether the z field is set.
     */
    @java.lang.Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }
    /**
     * <code>required double z = 3;</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(double value) {

      z_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required double z = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0D;
      onChanged();
      return this;
    }

    private boolean up_ ;
    /**
     * <code>required bool up = 4;</code>
     * @return Whether the up field is set.
     */
    @java.lang.Override
    public boolean hasUp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bool up = 4;</code>
     * @return The up.
     */
    @java.lang.Override
    public boolean getUp() {
      return up_;
    }
    /**
     * <code>required bool up = 4;</code>
     * @param value The up to set.
     * @return This builder for chaining.
     */
    public Builder setUp(boolean value) {

      up_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>required bool up = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      up_ = false;
      onChanged();
      return this;
    }

    private boolean down_ ;
    /**
     * <code>required bool down = 5;</code>
     * @return Whether the down field is set.
     */
    @java.lang.Override
    public boolean hasDown() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool down = 5;</code>
     * @return The down.
     */
    @java.lang.Override
    public boolean getDown() {
      return down_;
    }
    /**
     * <code>required bool down = 5;</code>
     * @param value The down to set.
     * @return This builder for chaining.
     */
    public Builder setDown(boolean value) {

      down_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>required bool down = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDown() {
      bitField0_ = (bitField0_ & ~0x00000010);
      down_ = false;
      onChanged();
      return this;
    }

    private boolean left_ ;
    /**
     * <code>required bool left = 6;</code>
     * @return Whether the left field is set.
     */
    @java.lang.Override
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required bool left = 6;</code>
     * @return The left.
     */
    @java.lang.Override
    public boolean getLeft() {
      return left_;
    }
    /**
     * <code>required bool left = 6;</code>
     * @param value The left to set.
     * @return This builder for chaining.
     */
    public Builder setLeft(boolean value) {

      left_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>required bool left = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeft() {
      bitField0_ = (bitField0_ & ~0x00000020);
      left_ = false;
      onChanged();
      return this;
    }

    private boolean right_ ;
    /**
     * <code>required bool right = 7;</code>
     * @return Whether the right field is set.
     */
    @java.lang.Override
    public boolean hasRight() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required bool right = 7;</code>
     * @return The right.
     */
    @java.lang.Override
    public boolean getRight() {
      return right_;
    }
    /**
     * <code>required bool right = 7;</code>
     * @param value The right to set.
     * @return This builder for chaining.
     */
    public Builder setRight(boolean value) {

      right_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>required bool right = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRight() {
      bitField0_ = (bitField0_ & ~0x00000040);
      right_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Sky9th.Protobuf.Transform)
  }

  // @@protoc_insertion_point(class_scope:Sky9th.Protobuf.Transform)
  private static final com.sky9th.game.chat.proto.Transform DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sky9th.game.chat.proto.Transform();
  }

  public static com.sky9th.game.chat.proto.Transform getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Transform>
      PARSER = new com.google.protobuf.AbstractParser<Transform>() {
    @java.lang.Override
    public Transform parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transform> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transform> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sky9th.game.chat.proto.Transform getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

